requires 'perl' => '5.010001';
requires 'Carp';
requires 'Digest::SHA';
requires 'List::Util' => '1.33';
requires 'Minion' => '8.0';
requires 'Mojolicious' => '7.0';
requires 'Mojo::Redis2' => '0.28';
requires 'Sys::Hostname';
requires 'Time::HiRes';
test_requires 'Test::More' => '0.88';
test_requires 'POSIX';
author_requires 'Minion' => '8.01';
